### ISSUE TITLE
Can't enable this command on Linux

### ISSUE THREAD

**Issue by Syakhisk** [slhsxcmy/vscode-double-line-numbers#2]
I was unable to use the extensions command on linux,
the error was:
`Double Line Numbers: Absolute + Relative' resulted in an error (command 'vscode-double-line-numbers.abs_rel' not found)`.
BTW, thank you for the extension!

**Comment by Ivo-Evans** [comment]
For anyone else having this issue, this [deprecated extension](https://marketplace.visualstudio.com/items?itemName=extr0py.vscode-relative-line-numbers) did work for me

**Comment by slhsxcmy** [comment]
Thanks for filing the issue, will look into this!

**Comment by benjamin-rood** [comment]
Yep, also on Linux, same thing. As OP said, thanks for doing this, let us know if you get time to patch it for Linux or if you want a hand testing the fix.

**Comment by ScopeSV** [comment]
Same thing on MacOS

**Comment by slhsxcmy** [comment]
> Same thing on MacOS

@sbvalois That is weird.. It was fine on my MacOS 10 but stopped working too when I upgraded to MacOS 11... Can you confirm your OS version?

Apologies for the delay due to a busy semester + internship + looking for full-time jobs... Hopefully getting settled soon and will have time to take care of this extension.

**Comment by slhsxcmy** [comment]
Hey guys, I published a new version (0.1.1). Could you try it out and see if it works? Thanks :)
@Syakhisk @Ivo-Evans @benjamin-rood @sbvalois

**Comment by refi64** [comment]
Not the original reporter, but I just installed this on an up-to-date Linux install, and it's working perfectly.

**Comment by slhsxcmy** [comment]
@refi64 Thanks! Closing this issue then :)
