### ISSUE TITLE
Used in VSCode vim

### ISSUE THREAD

**Issue by ycpss91255** [slhsxcmy/vscode-double-line-numbers#3]
Hi
I found a bug
The problem of using vscode vim and double line number at the same time

![Screenshot from 2021-11-13 23-46-09](https://user-images.githubusercontent.com/54975526/141650104-5fab8170-7b3c-45d5-82b2-244d5e1b8e68.png)

**Comment by slhsxcmy** [comment]
@ycpss91255 Hello, the screenshot seems to be an older version. Did you try the latest version? Please let me know if there's a problem with the latest version (0.1.1) :)

**Comment by ycpss91255** [comment]
Hello, everything is ok in the v0.1.1 version, thank you
