### ISSUE TITLE
Cannot add breakpoints unless line above is selected

### ISSUE THREAD

**Issue by itsknob** [slhsxcmy/vscode-double-line-numbers#4]
![image](https://user-images.githubusercontent.com/8973405/146203481-f2edf3a9-9b56-44d0-bbc3-4bf9dde61e6c.png)

When "Relative + Absolute" is selected I can only place a breakpoint on the line that is selected (21 in the picture) because there is no number in the left most column, when I try to select another line (20, or 22, or 23) to add a breakpoint I am unable to do so.

I would like to be able to place a break point on any valid line, regardless of where the line is selected or not.

While double checking, it looks like Off, Relative, and Absolute are working great! However, on "Absolute + Relative" I'm unable to place breakpoints whatsoever! Then on "Relative + Absolute" I am able to place on the selected line, **but it looks like both sets of line numbers are relative.** Though that last point, may be because I have my line numbers set up to relative by default.

I hope this information helps. 

Line Numbers Off:
![image](https://user-images.githubusercontent.com/8973405/146204004-7218ec17-9ae3-4496-8937-4f4ec4fb2e2b.png)

Absolute:
![image](https://user-images.githubusercontent.com/8973405/146204048-92bfaa2f-929b-43a8-a5ce-5362fb927363.png)

Relative:
![image](https://user-images.githubusercontent.com/8973405/146204141-72e32229-34fa-4270-a0b6-ea7efaa70019.png)

Absolute + Relative:
![image](https://user-images.githubusercontent.com/8973405/146204199-5f00d5e4-ba8c-40b4-ba3f-97dde21e90e6.png)

Relative + Absolute:
![image](https://user-images.githubusercontent.com/8973405/146204288-7fdb160b-5dd7-4b57-857b-3cc7a5fe0333.png)

**Comment by slhsxcmy** [comment]
Hi, thanks for using my extension! Unfortunately, this is a [long-lasting known issue of VSCode](https://github.com/microsoft/vscode/issues/5923) :( I'll keep this issue open though to track updates from Microsoft.

**Comment by itsknob** [comment]
Oh that's unfortunate! Thanks for linking the relevant issue! I'll keep an eye on it.

**Comment by slhsxcmy** [comment]
Looping back after 1.5 years :) VSCode 1.79 added support for a separate breakpoint lane. [More context](https://github.com/microsoft/vscode/pull/180013). It allows right click on the gutter to add breakpoint.

<img width="280" alt="Screen Shot 2023-07-27 at 8 03 43 PM" src="https://github.com/slhsxcmy/vscode-double-line-numbers/assets/20136533/3af170ec-4d58-4bb9-8c4e-fd5e7bbed383">
<img width="111" alt="Screen Shot 2023-07-27 at 8 03 53 PM" src="https://github.com/slhsxcmy/vscode-double-line-numbers/assets/20136533/0341cb48-ea84-462f-9e27-180b99584db4">
